name: cruisemonkey
description: The client application for the cruise, for Android and iOS. Connects to the Twitarr server.

dependencies:
  flutter:
    sdk: flutter
  path_provider: any
  image_picker: any
  intl: ^0.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - images/deck_1.png
   - images/deck_2.png
   - images/deck_3.png
   - images/deck_4.png
   - images/deck_5.png
   - images/deck_6.png
   - images/deck_7.png
   - images/deck_8.png
   - images/deck_9.png
   - images/deck_10.png
   - resources/JoCoKaraokeSongCatalog.txt
