name: cruisemonkey
description: The client application for the cruise, for Android and iOS. Connects to the Twitarr server.

dependencies:
  flutter:
    sdk: flutter
  path_provider: any
  flutter_local_notifications: ^0.4.5
  image_picker: #any
    path: ../plugins/packages/image_picker/
  android_alarm_manager: #any
    path: ../plugins/packages/android_alarm_manager/
  sqflite: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any

flutter_icons:
  # update with: flutter packages pub run flutter_launcher_icons:main
  # create notification icon with: convert icons/foreground.png -trim +repage android/app/src/main/res/drawable/notifications.png
  android: true
  ios: true
  image_path: icons/cruise_monkey.png
  adaptive_icon_background: icons/background.png
  adaptive_icon_foreground: icons/foreground.png

flutter:
  uses-material-design: true
  assets:
   - images/deck_1.png
   - images/deck_2.png
   - images/deck_3.png
   - images/deck_4.png
   - images/deck_5.png
   - images/deck_6.png
   - images/deck_7.png
   - images/deck_8.png
   - images/deck_9.png
   - images/deck_10.png
   - resources/JoCoKaraokeSongCatalog.txt
