name: cruisemonkey
description: The client application for the cruise, for Android and iOS. Connects to the Twitarr server.

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager: any
  battery_optimization: any
  flutter_local_notifications: any
  image_picker: any
  path_provider: any
  pedantic: any
  photo_view: any
  sqflite: any
  url_launcher: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any

flutter_icons:
  # The core inputs are icons/foreground.png and icons/background.png.
  # Run "update_icons.sh" to update the rest. Needs imagemagick installed.
  android: true
  ios: true
  image_path: icons/cruise_monkey.png
  adaptive_icon_background: icons/background.png
  adaptive_icon_foreground: icons/foreground.png

flutter:
  uses-material-design: true
  assets:
   - images/deck_1.png
   - images/deck_2.png
   - images/deck_3.png
   - images/deck_4.png
   - images/deck_5.png
   - images/deck_6.png
   - images/deck_7.png
   - images/deck_8.png
   - images/deck_9.png
   - images/deck_10.png
   - images/deck_11.png
   - resources/JoCoKaraokeSongCatalog.txt
   - resources/JoCoGamesCatalog.txt
   - images/cruise_monkey.png
   - images/emoji/
